<SplashScreen>:
    MDFloatLayout:
        md_bg_color: '#FFF2F2'
        Image:
            source: 'image/logo.png'
            size_hint: None, None
            size: "128dp", "128dp"
            pos_hint: {"center_x": 0.5, "center_y": 0.6}
        MDLabel:
            text: "Cargando..."
            halign: "center"
            pos_hint: {"center_x": 0.5, "center_y": 0.4}
            theme_text_color: "Custom"
            text_color: '#111111'
            font_style: "H5"